# Default command lists all available recipes
_default:
	@just --list

# clean all python build/compilation files and directories
clean:
	find . -name '*.pyc' -exec rm --force {} +
	find . -name '*.pyo' -exec rm --force {} +
	find . -name '*~' -exec rm --force {} +
	rm --force .coverage
	rm --force --recursive .pytest_cache
	rm --force --recursive build/
	rm --force --recursive dist/
	rm --force --recursive *.egg-info

# install dependencies in local venv, GDAL will be installed from wheel file.
venv:
	uv sync --group test --group dev

# install dependencies in local venv, but assumes GDAL is preinstalled on the system.
venv-no-gdal:
	uv sync --group test --group dev --no-install-package gdal && uv pip install gdal=="$(shell gdal-config --version).*"

# run test with coverage
test:
	uv run pytest tests/ -rsx --verbose --color=yes --cov={{cookiecutter.project_slug}} --cov-report term-missing

# Write the version and commit hash to python file
version:
	echo -e "__version__ = \"$(shell git describe --always --tags --abbrev=0)\"\n__commit__ = \"$(shell git rev-parse --short HEAD)\"" > src/{{cookiecutter.project_slug}}/_version.py

#  build the package ready for distribution and update the version tag
dist: version
	uv build

# lint python code using ruff
lint:
	uvx ruff check . --fix

# format python code using ruff
format:
	uvx ruff format .

# run the type checker ty
types:
	uvx ty check

# lint and format python code using ruff and run the type checker
check: lint format types

# setup the pre-commit hooks
hooks:
	uvx pre-commit install
